In [1]:
# tensorflow와 tf.keras를 임포트합니다
from tensorflow import keras
from keras import layers

# 헬퍼(helper) 라이브러리를 임포트합니다
import numpy as np
import matplotlib.pyplot as plt

print(tf.__version__)

2.3.0


## 퍼셉트론

In [25]:
X=np.random.rand(1,5)

In [26]:
# 퍼셉트론의 생성
l=layers.Dense(1,input_shape=[5])

In [27]:
# 퍼셉트론 처리 예시
l(X)

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[-0.22671486]], dtype=float32)>

## 퍼셉트론 (출력층이 여러개)

In [28]:
l=layers.Dense(3,input_shape=[5])
l(X)

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[-0.17707181, -0.46154618,  0.2624218 ]], dtype=float32)>

## 퍼셉트론 (활성화 함수)

In [32]:
# l=layers.Dense(3,input_shape=[5],activation='sigmoid')
# l=layers.Dense(3,input_shape=[5],activation='tanh')
l=layers.Dense(3,input_shape=[5],activation='relu')
l(X)

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[0.        , 0.        , 0.40749055]], dtype=float32)>

## 한번에 여러 raw 처리

In [38]:
X=np.random.rand(10,5)
l(X)

<tf.Tensor: shape=(10, 3), dtype=float32, numpy=
array([[0.25821438, 0.        , 0.30302307],
       [0.        , 0.024234  , 0.        ],
       [0.        , 0.26446956, 0.        ],
       [0.        , 0.3540004 , 0.        ],
       [0.3926993 , 0.13362402, 0.22552997],
       [0.34777683, 0.        , 0.13760124],
       [0.44034895, 0.        , 0.37950408],
       [0.12287876, 0.        , 0.05539165],
       [0.        , 0.36369824, 0.        ],
       [0.01508637, 0.10865192, 0.        ]], dtype=float32)>

## Deep Neural Network 만들기

### keras.Sequential를 사용해 모델만들기

In [41]:
import numpy as np
X=np.random.rand(1,5)

In [42]:
model = keras.Sequential([
    layers.Dense(5, input_shape=[5], activation='relu'),
    #layers.Dense(1, activation='relu')
])

In [43]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_16 (Dense)             (None, 5)                 30        
Total params: 30
Trainable params: 30
Non-trainable params: 0
_________________________________________________________________


In [44]:
model(X)

<tf.Tensor: shape=(1, 5), dtype=float32, numpy=
array([[0.        , 0.12371477, 0.        , 0.32808036, 0.        ]],
      dtype=float32)>

### 모델에 층 추가하기

In [49]:
X=np.random.rand(1,10)

In [54]:
model = keras.Sequential([
    layers.Dense(5, input_shape=[10], activation='relu'),
#     layers.Dense(3, input_shape=[5], activation='relu') # input_shape=[5]
    layers.Dense(3, activation='relu')
])
model.compile()

In [55]:
# 패러미터의 갯수가 왜 저렇게 나오는지 생각해 볼것
model.summary()

Model: "sequential_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_23 (Dense)             (None, 5)                 55        
_________________________________________________________________
dense_24 (Dense)             (None, 3)                 18        
Total params: 73
Trainable params: 73
Non-trainable params: 0
_________________________________________________________________


In [56]:
model(X)

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[0.        , 0.        , 0.48856673]], dtype=float32)>

### 딥뉴럴 네트워크

In [58]:
model = keras.Sequential([
    layers.Dense(5, input_shape=[10], activation='relu'),
    layers.Dense(10,  activation='relu'), # input_shape=[5]
    layers.Dense(10,  activation='relu'), # input_shape=[5]
    layers.Dense(1,  activation='relu') # input_shape=[5]
])
model.compile()

In [59]:
model.summary()

Model: "sequential_6"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_25 (Dense)             (None, 5)                 55        
_________________________________________________________________
dense_26 (Dense)             (None, 10)                60        
_________________________________________________________________
dense_27 (Dense)             (None, 10)                110       
_________________________________________________________________
dense_28 (Dense)             (None, 1)                 11        
Total params: 236
Trainable params: 236
Non-trainable params: 0
_________________________________________________________________


In [60]:
model(X)

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[0.]], dtype=float32)>

## Flatten Layer

In [14]:
fashion_mnist = keras.datasets.fashion_mnist

(train_images, train_labels), (test_images, test_labels) = fashion_mnist.load_data()

In [15]:
model = keras.Sequential([
    layers.Flatten(input_shape=(28,28))
])

In [16]:
model.output_shape

(None, 784)

In [17]:
model.compile()

In [19]:
model.predict(train_images).shape

(60000, 784)

## 다양한 layer
- Convolution Layer
- LSTM Layer
- Embedding Layer..
