# 라이브러리 불러오기

In [ ]:
from tensorflow import keras # keras 고수준 api 불러오기
from keras import layers # 퍼셉트론으로 구성된 은닉층, 입력층, 출력층

import numpy as np
import matplotlib.pyplot as plt

## 퍼셉트론

In [ ]:
# 랜덤 데이터 생성
X = np.random.rand(1,5)
X

array([[0.27554744, 0.65903671, 0.79104006, 0.03621095, 0.27476271]])

In [ ]:
# 퍼셉트론
l=layers.Dense(1, input_shape=[5])

In [ ]:
l(X)

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[0.5393923]], dtype=float32)>

## 퍼셉트론 (출력층이 여러 개)

In [ ]:
l = layers.Dense(3,input_shape=[5])
l(X)

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[ 0.13687558, -0.5457355 , -1.159273  ]], dtype=float32)>

## 퍼셉트론 (활성화 함수)

In [ ]:
# l = layers.Dense(3, input_shape=[5], activation='sigmoid')
# l = layers.Dense(3, input_shape=[5], activation='tanh')
l = layers.Dense(3, input_shape=[5], activation='relu')
l(X)

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[0.24503528, 0.        , 0.78145385]], dtype=float32)>

## 한번에 여러 raw 처리

In [ ]:
X = np.random.rand(10,5)
X

array([[0.20942995, 0.78283728, 0.88669972, 0.26386121, 0.0130669 ],
       [0.46840124, 0.96597659, 0.07350835, 0.59361112, 0.0408333 ],
       [0.61721753, 0.91235031, 0.41619273, 0.61923972, 0.52322262],
       [0.55654313, 0.43314735, 0.27904022, 0.31840878, 0.40773521],
       [0.04573027, 0.19997545, 0.98624656, 0.25166215, 0.91859658],
       [0.58697132, 0.34151022, 0.61557683, 0.21199541, 0.64385041],
       [0.58811223, 0.06282425, 0.75759702, 0.16862143, 0.26610003],
       [0.93385939, 0.18432249, 0.89785364, 0.86464714, 0.98152376],
       [0.82006284, 0.36244593, 0.35566718, 0.09827343, 0.921831  ],
       [0.83652049, 0.50134615, 0.86767753, 0.41803355, 0.71343924]])

In [ ]:
l(X)

<tf.Tensor: shape=(10, 3), dtype=float32, numpy=
array([[0.19482738, 0.        , 0.8817548 ],
       [0.2682322 , 0.        , 0.1461054 ],
       [0.45426908, 0.        , 0.22641692],
       [0.12455227, 0.        , 0.16708212],
       [0.69677925, 0.        , 0.34363985],
       [0.17187284, 0.        , 0.3778517 ],
       [0.        , 0.        , 0.61660314],
       [0.16772659, 0.        , 0.18506454],
       [0.21969005, 0.        , 0.16346538],
       [0.12097018, 0.        , 0.5698775 ]], dtype=float32)>

# Deep neural network 만들기

## keras.Sequential을 이용해 모델만들기

In [ ]:
X = np.random.rand(1,5)
X

array([[0.59723998, 0.82850554, 0.75037699, 0.47889264, 0.71268638]])

In [ ]:
model = keras.Sequential([
                          layers.Dense(3,input_shape=[5],activation='relu')
                          ])

In [ ]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_6 (Dense)              (None, 3)                 18        
Total params: 18
Trainable params: 18
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model(X)

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[0.64895505, 0.6669186 , 1.2224698 ]], dtype=float32)>

## keras.Sequential에 층 추가하기

In [ ]:
X = np.random.rand(1,10)
X

array([[0.92690456, 0.18266836, 0.53864247, 0.65006688, 0.69820524,
        0.28896389, 0.52836743, 0.60760152, 0.13164702, 0.16683157]])

In [ ]:
model = keras.Sequential([
                          layers.Dense(5,input_shape=[10],activation='relu'),
                          layers.Dense(3,activation='sigmoid') # 두번째 층부터는 input_shape를 알아서 추론한다.
])
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_9 (Dense)              (None, 5)                 55        
_________________________________________________________________
dense_10 (Dense)             (None, 3)                 18        
Total params: 73
Trainable params: 73
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model(X)

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[0.39657706, 0.3162153 , 0.48907363]], dtype=float32)>

## 딥 뉴럴 네트워크

In [ ]:
model = keras.Sequential([
    layers.Dense(5, input_shape=[10], activation='relu'),
    layers.Dense(10,  activation='relu'), 
    layers.Dense(10,  activation='relu'), 
    layers.Dense(1,  activation='relu') 
])
model.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_11 (Dense)             (None, 5)                 55        
_________________________________________________________________
dense_12 (Dense)             (None, 10)                60        
_________________________________________________________________
dense_13 (Dense)             (None, 10)                110       
_________________________________________________________________
dense_14 (Dense)             (None, 1)                 11        
Total params: 236
Trainable params: 236
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model(X)

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[0.41036972]], dtype=float32)>

## layer의 유형

In [ ]:
layers.